### ISSUE TITLE
One forgotten TODO 

### ISSUE THREAD

**Issue by cermmik** [Trace-Share/Trace-Normalizer#10]
https://github.com/Trace-Share/Trace-Normalizer/blob/14806073ad87ec3609e2c5b817535bc9914f9258/crawler.py#L317

**Comment by cermmik** [comment]
The same TODO is also in the normalizer.

**Comment by TomasMadeja** [comment]
Description added as of f2fb0d8d73891aa1a2f48db407e7dc353f1369f2
