### ISSUE TITLE
Define default output file for crawler

### ISSUE THREAD

**Issue by cermmik** [Trace-Share/Trace-Normalizer#2]
Set default output file name for argument --output .

**Comment by TomasMadeja** [comment]
Now accepts output directory as `--output` with default output file name `normalized_<pcap name`.
`--output` is now optional with default current directory as default.
c5122453876dcec10e2cfff9f734162eb87a1cbc

**Comment by cermmik** [comment]
Please update Crawler in a similar way.

**Comment by TomasMadeja** [comment]
Crawler now accepts directory as output or defaults to pcap path. 4789cd2a29c1b26693f89c1d733adb74a6b195ee
