### ISSUE TITLE
Simplify HTML IP address parser in crawler

### ISSUE THREAD

**Issue by cermmik** [Trace-Share/Trace-Normalizer#3]
IP searching in HTML finds non-address strings. Reduce regular expressions to search for common address strings only. Maybe add info about address source (connection, HTML, DNS, ...) to the output YAML file.

When using the attached file [test.zip](https://github.com/Trace-Share/Trace-Normalizer/files/3367280/test.zip) the crawler produces two incorrectly identified addresses `7.0.5.010` and `'::'`.

**Comment by TomasMadeja** [comment]
IPv4 and IPv6 matching now checks for some leading and tailing characters. Output yaml now provides info about matched protocols, first occurance and number of occurances. 992f1e288a8e18753dd5073dbf4ca37db59e47b8

**Comment by TomasMadeja** [comment]
Crawler and Normalizer ignore (some) IP and MAC addresses with special meaning. ee3cf53a656e532ee2d2687553956ed2e01f1e76
